version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3080:3080"
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      - transcendent-network
    volumes:
      - ./server:/server
    command: >
      bash -c "cp -rfu /cache/node_modules/. /server/node_modules/ &&
      npx prisma migrate dev --name init &&
      npm run start:dev"

  database:
    image: postgres:12.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    restart: on-failure
    networks:
      - transcendent-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    ports:
      - "3090:3090" 
    networks:
      - transcendent-network
    volumes:
      - ./app:/app
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
    restart: on-failure
  
networks:
  transcendent-network:

volumes:
  postgres-data:
